theme: jekyll-theme-minimal
title: Welcome to Darby Maguire's website!
description: Feel free to use this to get to know me better as a coder and person.

![image](https://user-images.githubusercontent.com/77426275/104655606-eeb1ba80-568b-11eb-9d37-7a1a2e2163c9.png)

